# Generated by Django 3.2.4 on 2021-07-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_asktobeadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asktobeadmin',
            name='user',
        ),
        migrations.AddField(
            model_name='asktobeadmin',
            name='worker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.worker'),
        ),
    ]
