# Generated by Django 3.2.4 on 2021-07-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_auto_20210711_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='asktobeadmin',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
